---

- name: Install epel from remote repo
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm state=present
  sudo: Yes
  register: epel

- name: Install webtatic from remote repo
  yum: name=https://mirror.webtatic.com/yum/el6/latest.rpm state=present
  sudo: Yes
  register: webtatic

- name: Upgrade all packages
  yum: name=* state=latest
  sudo: Yes
  when: epel.changed or webtatic.changed

- name: Install php
  yum: name={{ item }} enablerepo=webtatic state=present
  sudo: Yes
  with_items:
    - php70w-fpm
    - php70w-common
    - php70w-cli
    - php70w-devel
    - php70w-pear
    - php70w-mcrypt
    - php70w-pecl-apcu-5.1.3
    - php70w-opcache
    - php70w-pdo
    - php70w-mysql
    - php70w-pecl-redis
    - pcre-devel
    - gcc
    - make

- name: Install nginx
  yum: name=nginx enablerepo=epel state=present
  sudo: Yes

- name: Put php-fpm.conf
  template: src=php-fpm.conf dest=/etc/php-fpm.d/www.conf
  sudo: Yes

- name: Put apcu.ini
  template: src=apcu.ini dest=/etc/php.d/apcu.ini
  sudo: Yes

- name: Put opcache.ini
  template: src=opcache.ini dest=/etc/php.d/opcache.ini
  sudo: Yes

- name: Put opcache-default.blacklist
  template: src=opcache-default.blacklist dest=/etc/php.d/opcache-default.blacklist
  sudo: Yes

- name: Change Permission php-fpm log
  file: path=/var/log/php-fpm owner={{ user_fpm }} group={{ user_fpm }} mode=0775 state=directory
  sudo: Yes

- name: Restart php-fpm
  service: name=php-fpm enabled=yes state=restarted
  sudo: Yes

- name: Check phalcon
  file: path=/opt/cphalcon state=directory
  sudo: Yes
  register: phalcon

- name: Clone phalcon
  command: git clone git://github.com/phalcon/cphalcon.git /opt/cphalcon
  sudo: Yes
  when: phalcon.changed

- name: Install phalcon
  command: ./install chdir=/opt/cphalcon/build
  sudo: Yes
  when: phalcon.changed

- name: Put phalcon.ini
  template: src=phalcon.ini dest=/etc/php.d/phalcon.ini
  sudo: Yes

- name: Restart php-fpm
  service: name=php-fpm enabled=yes state=restarted
  sudo: Yes

- name: Put nginx.conf
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  sudo: Yes

- name: Put nginx-default.conf
  template: src=nginx-default.conf dest=/etc/nginx/conf.d/default.conf
  sudo: Yes

- name: Change Permission nginx log
  file: path=/var/log/nginx owner={{ user_nginx }} group={{ user_nginx }} mode=0775 state=directory
  sudo: Yes

- name: Restart nginx
  service: name=nginx enabled=yes state=restarted
  sudo: Yes
