---

- name: Check selinux
  command: getenforce
  register: getenforce
  sudo: Yes
  changed_when: False

- name: Stop selinux
  command: setenforce 0
  sudo: Yes
  when: getenforce.stdout.find('Enforcing') != -1

- name: Put selinux/config
  sudo: Yes
  template: src=selinux.config dest=/etc/selinux/config

- name: Stop iptabes
  sudo: Yes
  service: name=iptables enabled=no state=stopped

- name: Set Jst
  sudo: Yes
  command: cp /usr/share/zoneinfo/Japan /etc/localtime

- name: Install git
  sudo: Yes
  yum: name=git state=present
